config/routes.rb
UFOScraper::Application.routes.draw do
  
  

  resources :shape_categories

  resources :weather_stations

  resources :sightings

  match 'scrapers/sighting_ws_distance', :to => 'scrapers#sighting_ws_distance'
  match 'scrapers/sighting_airport_distance', :to => 'scrapers#sighting_airport_distance'
  match 'scrapers/weatherstation_scraper', :to => 'scrapers#weatherstation_scraper'
  match 'scrapers/city_scraper', :to => 'scrapers#city_scraper'
  match 'scrapers/airport_scraper', :to => 'scrapers#airport_scraper'
  match 'scrapers/sighting_scraper', :to => 'scrapers#sighting_scraper'
  
  resources :airports
  
  resources :scrapers

  resources :cities

  resources :states

end

app/models/shape_category.rb
class ShapeCategory < ActiveRecord::Base
end

app/controllers/shape_categories_controller.rb
class ShapeCategoriesController < ApplicationController
  # GET /shape_categories
  # GET /shape_categories.xml
  def index
    @shape_categories = ShapeCategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @shape_categories }
    end
  end

  # GET /shape_categories/1
  # GET /shape_categories/1.xml
  def show
    @shape_category = ShapeCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @shape_category }
    end
  end

  # GET /shape_categories/new
  # GET /shape_categories/new.xml
  def new
    @shape_category = ShapeCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @shape_category }
    end
  end

  # GET /shape_categories/1/edit
  def edit
    @shape_category = ShapeCategory.find(params[:id])
  end

  # POST /shape_categories
  # POST /shape_categories.xml
  def create
    @shape_category = ShapeCategory.new(params[:shape_category])

    respond_to do |format|
      if @shape_category.save
        format.html { redirect_to(@shape_category, :notice => 'Shape category was successfully created.') }
        format.xml  { render :xml => @shape_category, :status => :created, :location => @shape_category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @shape_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /shape_categories/1
  # PUT /shape_categories/1.xml
  def update
    @shape_category = ShapeCategory.find(params[:id])

    respond_to do |format|
      if @shape_category.update_attributes(params[:shape_category])
        format.html { redirect_to(@shape_category, :notice => 'Shape category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @shape_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /shape_categories/1
  # DELETE /shape_categories/1.xml
  def destroy
    @shape_category = ShapeCategory.find(params[:id])
    @shape_category.destroy

    respond_to do |format|
      format.html { redirect_to(shape_categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/shape_categories_helper.rb
module ShapeCategoriesHelper
end

app/views/shape_categories/_form.html.erb
<%= form_for(@shape_category) do |f| %>
  <% if @shape_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shape_category.errors.count, "error") %> prohibited this shape_category from being saved:</h2>

      <ul>
      <% @shape_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shape_categories/edit.html.erb
<h1>Editing shape_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @shape_category %> |
<%= link_to 'Back', shape_categories_path %>

app/views/shape_categories/index.html.erb
<h1>Listing shape_categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shape_categories.each do |shape_category| %>
  <tr>
    <td><%= shape_category.name %></td>
    <td><%= link_to 'Show', shape_category %></td>
    <td><%= link_to 'Edit', edit_shape_category_path(shape_category) %></td>
    <td><%= link_to 'Destroy', shape_category, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shape category', new_shape_category_path %>

app/views/shape_categories/new.html.erb
<h1>New shape_category</h1>

<%= render 'form' %>

<%= link_to 'Back', shape_categories_path %>

app/views/shape_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @shape_category.name %>
</p>


<%= link_to 'Edit', edit_shape_category_path(@shape_category) %> |
<%= link_to 'Back', shape_categories_path %>