config/routes.rb
UFOScraper::Application.routes.draw do
  
  

  resources :shape_categories

  resources :weather_stations

  resources :sightings

  match 'scrapers/sighting_ws_distance', :to => 'scrapers#sighting_ws_distance'
  match 'scrapers/sighting_airport_distance', :to => 'scrapers#sighting_airport_distance'
  match 'scrapers/weatherstation_scraper', :to => 'scrapers#weatherstation_scraper'
  match 'scrapers/city_scraper', :to => 'scrapers#city_scraper'
  match 'scrapers/airport_scraper', :to => 'scrapers#airport_scraper'
  match 'scrapers/sighting_scraper', :to => 'scrapers#sighting_scraper'
  
  resources :airports
  
  resources :scrapers

  resources :cities

  resources :states

end

app/models/airport.rb
class Airport < ActiveRecord::Base
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  # GET /airports
  # GET /airports.xml
  def index
    @airports = Airport.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @airports }
    end
  end

  # GET /airports/1
  # GET /airports/1.xml
  def show
    @airport = Airport.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @airport }
    end
  end

  # GET /airports/new
  # GET /airports/new.xml
  def new
    @airport = Airport.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @airport }
    end
  end

  # GET /airports/1/edit
  def edit
    @airport = Airport.find(params[:id])
  end

  # POST /airports
  # POST /airports.xml
  def create
    @airport = Airport.new(params[:airport])

    respond_to do |format|
      if @airport.save
        format.html { redirect_to(@airport, :notice => 'Airport was successfully created.') }
        format.xml  { render :xml => @airport, :status => :created, :location => @airport }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @airport.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /airports/1
  # PUT /airports/1.xml
  def update
    @airport = Airport.find(params[:id])

    respond_to do |format|
      if @airport.update_attributes(params[:airport])
        format.html { redirect_to(@airport, :notice => 'Airport was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @airport.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /airports/1
  # DELETE /airports/1.xml
  def destroy
    @airport = Airport.find(params[:id])
    @airport.destroy

    respond_to do |format|
      format.html { redirect_to(airports_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/views/airports/_form.html.erb
<%= form_for(@airport) do |f| %>
  <% if @airport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@airport.errors.count, "error") %> prohibited this airport from being saved:</h2>

      <ul>
      <% @airport.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :icao %><br />
    <%= f.text_field :icao %>
  </div>
  <div class="field">
    <%= f.label :iata %><br />
    <%= f.text_field :iata %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :cities_id %><br />
    <%= f.text_field :cities_id %>
  </div>
  <div class="field">
    <%= f.label :lat_deg %><br />
    <%= f.text_field :lat_deg %>
  </div>
  <div class="field">
    <%= f.label :lat_min %><br />
    <%= f.text_field :lat_min %>
  </div>
  <div class="field">
    <%= f.label :lat_sec %><br />
    <%= f.text_field :lat_sec %>
  </div>
  <div class="field">
    <%= f.label :lat_dir %><br />
    <%= f.text_field :lat_dir %>
  </div>
  <div class="field">
    <%= f.label :lon_deg %><br />
    <%= f.text_field :lon_deg %>
  </div>
  <div class="field">
    <%= f.label :lon_min %><br />
    <%= f.text_field :lon_min %>
  </div>
  <div class="field">
    <%= f.label :lon_sec %><br />
    <%= f.text_field :lon_sec %>
  </div>
  <div class="field">
    <%= f.label :lon_dir %><br />
    <%= f.text_field :lon_dir %>
  </div>
  <div class="field">
    <%= f.label :altitude %><br />
    <%= f.text_field :altitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/airports/edit.html.erb
<h1>Editing airport</h1>

<%= render 'form' %>

<%= link_to 'Show', @airport %> |
<%= link_to 'Back', airports_path %>

app/views/airports/index.html.erb
<h1>Listing airports</h1>

<table>
  <tr>
    <th>Icao</th>
    <th>Iata</th>
    <th>Name</th>
    <th>Cities</th>
    <th>Lat deg</th>
    <th>Lat min</th>
    <th>Lat sec</th>
    <th>Lat dir</th>
    <th>Lon deg</th>
    <th>Lon min</th>
    <th>Lon sec</th>
    <th>Lon dir</th>
    <th>Altitude</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @airports.each do |airport| %>
  <tr>
    <td><%= airport.icao %></td>
    <td><%= airport.iata %></td>
    <td><%= airport.name %></td>
    <td><%= airport.cities_id %></td>
    <td><%= airport.lat_deg %></td>
    <td><%= airport.lat_min %></td>
    <td><%= airport.lat_sec %></td>
    <td><%= airport.lat_dir %></td>
    <td><%= airport.lon_deg %></td>
    <td><%= airport.lon_min %></td>
    <td><%= airport.lon_sec %></td>
    <td><%= airport.lon_dir %></td>
    <td><%= airport.altitude %></td>
    <td><%= link_to 'Show', airport %></td>
    <td><%= link_to 'Edit', edit_airport_path(airport) %></td>
    <td><%= link_to 'Destroy', airport, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Airport', new_airport_path %>

app/views/airports/new.html.erb
<h1>New airport</h1>

<%= render 'form' %>

<%= link_to 'Back', airports_path %>

app/views/airports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Icao:</b>
  <%= @airport.icao %>
</p>

<p>
  <b>Iata:</b>
  <%= @airport.iata %>
</p>

<p>
  <b>Name:</b>
  <%= @airport.name %>
</p>

<p>
  <b>Cities:</b>
  <%= @airport.cities_id %>
</p>

<p>
  <b>Lat deg:</b>
  <%= @airport.lat_deg %>
</p>

<p>
  <b>Lat min:</b>
  <%= @airport.lat_min %>
</p>

<p>
  <b>Lat sec:</b>
  <%= @airport.lat_sec %>
</p>

<p>
  <b>Lat dir:</b>
  <%= @airport.lat_dir %>
</p>

<p>
  <b>Lon deg:</b>
  <%= @airport.lon_deg %>
</p>

<p>
  <b>Lon min:</b>
  <%= @airport.lon_min %>
</p>

<p>
  <b>Lon sec:</b>
  <%= @airport.lon_sec %>
</p>

<p>
  <b>Lon dir:</b>
  <%= @airport.lon_dir %>
</p>

<p>
  <b>Altitude:</b>
  <%= @airport.altitude %>
</p>


<%= link_to 'Edit', edit_airport_path(@airport) %> |
<%= link_to 'Back', airports_path %>