config/routes.rb
UFOScraper::Application.routes.draw do
  
  

  resources :shape_categories

  resources :weather_stations

  resources :sightings

  match 'scrapers/sighting_ws_distance', :to => 'scrapers#sighting_ws_distance'
  match 'scrapers/sighting_airport_distance', :to => 'scrapers#sighting_airport_distance'
  match 'scrapers/weatherstation_scraper', :to => 'scrapers#weatherstation_scraper'
  match 'scrapers/city_scraper', :to => 'scrapers#city_scraper'
  match 'scrapers/airport_scraper', :to => 'scrapers#airport_scraper'
  match 'scrapers/sighting_scraper', :to => 'scrapers#sighting_scraper'
  
  resources :airports
  
  resources :scrapers

  resources :cities

  resources :states

end

app/models/weather_station.rb
class WeatherStation < ActiveRecord::Base
end

app/controllers/weather_stations_controller.rb
class WeatherStationsController < ApplicationController
  # GET /weather_stations
  # GET /weather_stations.xml
  def index
    @weather_stations = WeatherStation.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @weather_stations }
    end
  end

  # GET /weather_stations/1
  # GET /weather_stations/1.xml
  def show
    @weather_station = WeatherStation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @weather_station }
    end
  end

  # GET /weather_stations/new
  # GET /weather_stations/new.xml
  def new
    @weather_station = WeatherStation.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @weather_station }
    end
  end

  # GET /weather_stations/1/edit
  def edit
    @weather_station = WeatherStation.find(params[:id])
  end

  # POST /weather_stations
  # POST /weather_stations.xml
  def create
    @weather_station = WeatherStation.new(params[:weather_station])

    respond_to do |format|
      if @weather_station.save
        format.html { redirect_to(@weather_station, :notice => 'Weather station was successfully created.') }
        format.xml  { render :xml => @weather_station, :status => :created, :location => @weather_station }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @weather_station.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /weather_stations/1
  # PUT /weather_stations/1.xml
  def update
    @weather_station = WeatherStation.find(params[:id])

    respond_to do |format|
      if @weather_station.update_attributes(params[:weather_station])
        format.html { redirect_to(@weather_station, :notice => 'Weather station was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @weather_station.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /weather_stations/1
  # DELETE /weather_stations/1.xml
  def destroy
    @weather_station = WeatherStation.find(params[:id])
    @weather_station.destroy

    respond_to do |format|
      format.html { redirect_to(weather_stations_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/weather_stations_helper.rb
module WeatherStationsHelper
end

app/views/weather_stations/_form.html.erb
<%= form_for(@weather_station) do |f| %>
  <% if @weather_station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weather_station.errors.count, "error") %> prohibited this weather_station from being saved:</h2>

      <ul>
      <% @weather_station.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nws %><br />
    <%= f.text_field :nws %>
  </div>
  <div class="field">
    <%= f.label :states_id %><br />
    <%= f.text_field :states_id %>
  </div>
  <div class="field">
    <%= f.label :cities_id %><br />
    <%= f.text_field :cities_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :lat_deg %><br />
    <%= f.text_field :lat_deg %>
  </div>
  <div class="field">
    <%= f.label :lat_min %><br />
    <%= f.text_field :lat_min %>
  </div>
  <div class="field">
    <%= f.label :lat_sec %><br />
    <%= f.text_field :lat_sec %>
  </div>
  <div class="field">
    <%= f.label :lat_dir %><br />
    <%= f.text_field :lat_dir %>
  </div>
  <div class="field">
    <%= f.label :lon_deg %><br />
    <%= f.text_field :lon_deg %>
  </div>
  <div class="field">
    <%= f.label :lon_min %><br />
    <%= f.text_field :lon_min %>
  </div>
  <div class="field">
    <%= f.label :lon_sec %><br />
    <%= f.text_field :lon_sec %>
  </div>
  <div class="field">
    <%= f.label :lon_dir %><br />
    <%= f.text_field :lon_dir %>
  </div>
  <div class="field">
    <%= f.label :elevation %><br />
    <%= f.text_field :elevation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weather_stations/edit.html.erb
<h1>Editing weather_station</h1>

<%= render 'form' %>

<%= link_to 'Show', @weather_station %> |
<%= link_to 'Back', weather_stations_path %>

app/views/weather_stations/index.html.erb
<h1>Listing weather_stations</h1>

<table>
  <tr>
    <th>Nws</th>
    <th>States</th>
    <th>Cities</th>
    <th>Name</th>
    <th>Lat deg</th>
    <th>Lat min</th>
    <th>Lat sec</th>
    <th>Lat dir</th>
    <th>Lon deg</th>
    <th>Lon min</th>
    <th>Lon sec</th>
    <th>Lon dir</th>
    <th>Elevation</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @weather_stations.each do |weather_station| %>
  <tr>
    <td><%= weather_station.nws %></td>
    <td><%= weather_station.states_id %></td>
    <td><%= weather_station.cities_id %></td>
    <td><%= weather_station.name %></td>
    <td><%= weather_station.lat_deg %></td>
    <td><%= weather_station.lat_min %></td>
    <td><%= weather_station.lat_sec %></td>
    <td><%= weather_station.lat_dir %></td>
    <td><%= weather_station.lon_deg %></td>
    <td><%= weather_station.lon_min %></td>
    <td><%= weather_station.lon_sec %></td>
    <td><%= weather_station.lon_dir %></td>
    <td><%= weather_station.elevation %></td>
    <td><%= link_to 'Show', weather_station %></td>
    <td><%= link_to 'Edit', edit_weather_station_path(weather_station) %></td>
    <td><%= link_to 'Destroy', weather_station, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Weather station', new_weather_station_path %>

app/views/weather_stations/new.html.erb
<h1>New weather_station</h1>

<%= render 'form' %>

<%= link_to 'Back', weather_stations_path %>

app/views/weather_stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nws:</b>
  <%= @weather_station.nws %>
</p>

<p>
  <b>States:</b>
  <%= @weather_station.states_id %>
</p>

<p>
  <b>Cities:</b>
  <%= @weather_station.cities_id %>
</p>

<p>
  <b>Name:</b>
  <%= @weather_station.name %>
</p>

<p>
  <b>Lat deg:</b>
  <%= @weather_station.lat_deg %>
</p>

<p>
  <b>Lat min:</b>
  <%= @weather_station.lat_min %>
</p>

<p>
  <b>Lat sec:</b>
  <%= @weather_station.lat_sec %>
</p>

<p>
  <b>Lat dir:</b>
  <%= @weather_station.lat_dir %>
</p>

<p>
  <b>Lon deg:</b>
  <%= @weather_station.lon_deg %>
</p>

<p>
  <b>Lon min:</b>
  <%= @weather_station.lon_min %>
</p>

<p>
  <b>Lon sec:</b>
  <%= @weather_station.lon_sec %>
</p>

<p>
  <b>Lon dir:</b>
  <%= @weather_station.lon_dir %>
</p>

<p>
  <b>Elevation:</b>
  <%= @weather_station.elevation %>
</p>


<%= link_to 'Edit', edit_weather_station_path(@weather_station) %> |
<%= link_to 'Back', weather_stations_path %>